language: php

php:
    - 7.2
    - 7.3

env:
    global:
        - CC_TEST_REPORTER_ID=3cb0149c1ae23214062407321730aa13a558d9e10aa7011e01282b5a46e7f100

install:
    - travis_retry composer self-update
    - travis_retry composer require php-coveralls/php-coveralls:2.1.* --dev
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
    - travis_retry curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter

before_script:
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
    - travis_retry php vendor/bin/php-coveralls --verbose
